import type { Metadata } from "next";
import { Geist, Geist_Mono, DM_Sans } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";
import UpLayout from "@/components/UpLayout";
import DownLayout from "@/components/DownLayout";
import { AuthProvider } from "@/contexts/AuthContext";

const dmSans = DM_Sans({
  variable: "--font-dm-sans",
  subsets: ["latin"],
  weight: ["400", "500", "700"],
});

const arupala = localFont({
  src: [
    {
      path: "../fonts/ArupalaGroteskTrial/ArupalaGroteskTrial-Regular.woff",
      weight: "400",
      style: "normal",
    },
    {
      path: "../fonts/ArupalaGroteskTrial/ArupalaGroteskTrial-Air.woff",
      weight: "400",
      style: "normal",
    },
    {
      path: "../fonts/ArupalaGroteskTrial/ArupalaGroteskTrial-AirItalic.woff",
      weight: "400",
      style: "normal",
    },
    {
      path: "../fonts/ArupalaGroteskTrial/ArupalaGroteskTrial-Italic.woff",
      weight: "400",
      style: "normal",
    },
    {
      path: "../fonts/ArupalaGroteskTrial/ArupalaGroteskTrial-Light.woff",
      weight: "300",
      style: "normal",
    },
    {
      path: "../fonts/ArupalaGroteskTrial/ArupalaGroteskTrial-LightIta.woff",
      weight: "300",
      style: "normal",
    },
    {
      path: "../fonts/ArupalaGroteskTrial/ArupalaGroteskTrial-SuperLt.woff",
      weight: "300",
      style: "normal",
    },
    {
      path: "../fonts/ArupalaGroteskTrial/ArupalaGroteskTrial-SuperLtIt.woff",
      weight: "300",
      style: "normal",
    },
    {
      path: "../fonts/ArupalaGroteskTrial/ArupalaGroteskTrial-MedIta.woff",
      weight: "500",
      style: "normal",
    },
    {
      path: "../fonts/ArupalaGroteskTrial/ArupalaGroteskTrial-Medium.woff",
      weight: "500",
      style: "normal",
    },
    {
      path: "../fonts/ArupalaGroteskTrial/ArupalaGroteskTrial-SemBdIta.woff",
      weight: "600",
      style: "normal",
    },
    {
      path: "../fonts/ArupalaGroteskTrial/ArupalaGroteskTrial-SemiBold.woff",
      weight: "600",
      style: "normal",
    },
    {
      path: "../fonts/ArupalaGroteskTrial/ArupalaGroteskTrial-Bold.woff",
      weight: "700",
      style: "normal",
    },
    {
      path: "../fonts/ArupalaGroteskTrial/ArupalaGroteskTrial-BoldIta.woff",
      weight: "700",
      style: "normal",
    },
    {
      path: "../fonts/ArupalaGroteskTrial/ArupalaGroteskTrial-SuperBdIt.woff",
      weight: "700",
      style: "normal",
    },
    {
      path: "../fonts/ArupalaGroteskTrial/ArupalaGroteskTrial-SuperBold.woff",
      weight: "700",
      style: "normal",
    },
    {
      path: "../fonts/ArupalaGroteskTrial/ArupalaGroteskTrial-Ultra.woff",
      weight: "800",
      style: "normal",
    },
    {
      path: "../fonts/ArupalaGroteskTrial/ArupalaGroteskTrial-UltraIta.woff",
      weight: "800",
      style: "normal",
    },
    {
      path: "../fonts/ArupalaGroteskTrial/ARUPALA VARIABLE TRIAL-VF.woff",
      weight: "100",
      style: "normal",
    },
  ],
  variable: "--font-arupala",
  adjustFontFallback: false,
});

export const metadata: Metadata = {
  title: "RotoPass | The Ulitimate Fantasy Football Resource by Matthew Berry",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${arupala.variable} ${dmSans.variable}`}>
        <AuthProvider>
          <UpLayout />
          {children}
          <DownLayout />
        </AuthProvider>
      </body>
    </html>
  );
}
